### ISSUE TITLE
I encountered this error using the original version. Can this error be resolved?

### ISSUE THREAD

**Issue by ZJDATY** [zihaomu/opencv_lite#2]
`[ERROR:0@3.422] global onnx_importer.cpp:1064 cv::dnn::dnn4_v20230620::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Expand]:(onnx_node!/models.33/Expand) from domain='ai.onnx'`

**Comment by zihaomu** [comment]
If you met an error with original opencv, please issue at opencv. 
The `opencv_ort` is experimental version. Currently, I only test it with Mac M1 chip, and it supports almost every ONNX model. You are welcome to try it.

**Comment by ZJDATY** [comment]
@zihaomu  This version has solved my problem, thank you very much. It did not report any errors during the model loading and inference stages.But I encountered some situations where the original dnn functions could not be used during use. 
For example:
```
cv::dnn::readNetFromDarknet();
net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
cv::dnn::NMSBoxes();
```
And there may be some functions that I haven't used.

I want to know whether these functions are deliberately discarded, or there are some conflicts temporarily, or there are other alternatives.

**Comment by zihaomu** [comment]
The plan of this project is the following:
Totally remove the old opencv dnn, and replaced it with ORT. 
Since the original dnn has support onnx but only a small subset, we want to do it in a different way. And in order to make developing works clear, we decide to remove all of them. 

So, it is deliberately discarded. Technically, we only support ONNX model under this version. Actually, almost all darknet models could find the corresponding onnx version.

**Comment by ZJDATY** [comment]
> The plan of this project is the following: Totally remove the old opencv dnn, and replaced it with ORT. Since the original dnn has support onnx but only a small subset, we want to do it in a different way. And in order to make developing works clear, we decide to remove all of them.
> 
> So, it is deliberately discarded. Technically, we only support ONNX model under this version. Actually, almost all darknet models could find the corresponding onnx version.

Okay!
